#Layanan Database

services:

  db-webdinamis:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: password!123
      MARIADB_DATABASE: dbcompro_2388010010
      MARIADB_USER: userwebdinamis_2388010010
      MARIADB_PASSWORD: o4B@ohWqM]kYPHE-
    volumes:
      - db_data:/var/lib/mysql
      - ./db_data/dbcompro_2388010010.sql:/docker-entrypoint-initdb.d/dbcompro_2388010010.sql:ro
    restart: always
    

  container-dinamis:
    image: ${DOCKERHUB_USERNAME}/web-dinamis_2388010010:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_USER: userwebdinamis_2388010010
      DB_PASSWORD: o4B@ohWqM]kYPHE-
      DB_NAME: dbcompro_2388010010
      DB_HOST: db-webdinamis
      NEXTAUTH_SECRET : ini-kdkdkdkdkdkkd-hdhdhdhdhdhdh-
      NEXTAUTH_URL : http://13.212.137.48/3000
    depends_on:
      - db-webdinamis
 
volumes:
  db_data: {}